PR#0001: Реализован логгер с использованием паттерна Strategy
albrettto/dp-2024-lab02 pull request #1
Opened 2024-10-25 07:15 UTC by albrettto

2024-10-25 07:41 UTC, vladushka2000 commented on log_strategy.py
> +class LogStrategy(ABC):
1) Слишком раздутый интерфейс, нарушен isp. Выдели основные методы, а остальные сделай приватными
2) Не нравится название класса. Именуем как сущность, избавляемся от паттернов в названии. Предлагаю Writer

2024-10-25 07:41 UTC, vladushka2000 commented on log_strategy.py
> +from abc import ABC, abstractmethod
Нет ни одной докстринги. Написать для всех классов и каждого метода

2024-10-25 07:44 UTC, vladushka2000 commented on logger.py
> +class Logger(Singleton):
Нету интерфейса для логгера

2024-10-25 07:45 UTC, vladushka2000 commented on logger.py
> +    def set_file_path(self, file_path: str):
у тебя этот метод будет иметь смысл только тогда, когда мы хотим писать в файл. Подумай, куда убрать создание пути к файлу, чтобы в консольном логгере мы не могли обратиться к этому методу

2024-10-25 07:55 UTC, Rognak commented on .github/workflows/python-package.yml
> +    branches: [ "feature" ]
Зачем этот фильтр?

2024-10-25 07:56 UTC, Rognak commented on test.py
> +        self.file_path = tempfile.TemporaryDirectory()  # Используем временную директорию
Как вариант. Ну лучше вообще не писать в тестах в файлы

2024-10-25 07:57 UTC, Rognak commented on test.py
> +        self.run_multithreaded_logging(logger, f"[INFO] Application started successfully 0")
Ты здесь всё привязал к многопоточке, зачем? Это можно вынести в отдельный тест кейс

2024-10-25 08:09 UTC, albrettto commented on .github/workflows/python-package.yml
> +    branches: [ "feature" ]
Чтобы запуск происходил при пуше новых коммитов в эту ветку

2024-10-25 08:18 UTC, Rognak commented on .github/workflows/python-package.yml
> +    branches: [ "feature" ]
Ты тем самым ограничиваешь себя. А что если мы продолжим разработку? Будут другие ветки и т.д.

2024-10-25 08:19 UTC, albrettto commented on .github/workflows/python-package.yml
> +    branches: [ "feature" ]
Ну в таком случае, лучше убрать. Я уберу тогда

2024-10-29 06:14 UTC, Rognak requested changes
Необходимо исправить замечания

2024-10-29 08:47 UTC, albrettto commented
Исправил замечания

2024-10-29 09:19 UTC, vladushka2000 commented on enums/level_enum.py
> +    TRACE = 1
зачем? Значение должно соответствовать названию. Ты потом должен оперировать полем value из LogLevel, а не name. В этом и смысл Enum - мы задаем поля, которые потом используем в коде, а значения этих полей мы можем подменять как нам удобно

2024-10-29 09:20 UTC, vladushka2000 commented on interfaces/ilogger.py
> +    def set_log_strategy(self, writer: Writer):
поменяй название метода на set_writer

2024-10-29 09:21 UTC, vladushka2000 commented on logger.py
> +        formatted_message = self._format_message(level.name, message)
вот тут должен быть как раз не level.name, а level.value

2024-10-29 09:23 UTC, vladushka2000 commented on writers.py
> +class FileLogWriter(Writer, FilePathManager):
не очень круто наследовать сразу несколько классов, лучше сделать через композицию. Ну ладно, я думаю и так нормально. Поведение таких классов, отнаследованных от нескольких сущностей сложно отслеживать. Особенно когда ты потом делаешь еще один дочерний класс, как UpperCaseFileLogWriter

2024-10-29 09:33 UTC, albrettto commented on logger.py
> +        formatted_message = self._format_message(level.name, message)
Исправил

2024-10-29 09:34 UTC, albrettto commented on interfaces/ilogger.py
> +    def set_log_strategy(self, writer: Writer):
Поменял

2024-10-29 09:34 UTC, albrettto commented on enums/level_enum.py
> +    TRACE = 1
Исправил

2024-10-29 09:35 UTC, vladushka2000 commented
теперь все нравится

2024-10-29 09:35 UTC, vladushka2000 approved these changes

2024-10-31 05:41 UTC, Rognak approved these changes

2024-10-31 05:41 UTC, merged